export const SEGMENTOS = [
  'Comércio',
  'Serviços',
  'Indústria',
  'Saúde/Clínica Médica',
  'Alimentação',
  'Moda e Vestuário',
  'Tecnologia',
  'Construção Civil',
  'Agronegócio',
  'Transporte e Logística',
  'Educação',
  'Imobiliário',
  'Beleza e Estética',
  'Advocacia/Consultoria',
  'Contabilidade',
  'Eventos',
  'Outros',
] as const
